### ISSUE TITLE
Improve Sirius usage

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#31]
Obeo’s good practices for VSM will be applied, including:
• Avoiding using EObject as domain class. 
• Use services instead of Java External Calls. (see Delete Connection tool in Cluster diagram)
• Migration to AQL to improve performances and readability of the VSM.
• Link Representation descriptions to the Ecore model(s)
• Fill in the ≪ Documentation ≫ properties

**Comment by mypsycho** [comment]
About "Avoiding using EObject as domain class", some mappings require it : port in Composition for example.

**Comment by mypsycho** [comment]
• Avoiding using EObject as domain class : Required by Xtext choices : 
• Use services instead of Java External Calls: No performance issue. It will be replaced when needed.
• Migration to AQL to improve performances and readability of the VSM (done except for Java External Call to refactor)
• Link Representation descriptions to the Ecore model(s) : done
• Fill in the ≪ Documentation ≫ properties : ODesign is produced by a detailed xtend descriptor.
