### ISSUE TITLE
Document the source generation at build time

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#38]
In POOSL IDE the generated source code is not contributed (It is generated at build time). This is a
really good practice. The generator version is properly set in the poosl.genmodel model, making the
generation reproducible. However, maintainer has to be aware that in order to update the EMF
generated to they have to:
• Change the version in the genmodel file
• Change the version of EMF/Ecore embedded during the build

**Comment by mypsycho** [comment]
After analysis, generated code for mwe2 should be committed (for source update reason).
mwe2 drags a lot of dependencies hense they should be move in a tooling project outside product build scope.

**Comment by mypsycho** [comment]
In /org.eclipse.poosl.model/workflow/GenerateModels.mwe2
generateEdit is set false because the project does not follow the generation gap pattern of mwe2.
Unfortunately, there is little doc on this pattern. (org.eclipse.emf.mwe2.ecore.EcoreGenerator magic)

I will create 'src' and 'src-gen' folder to separate automatic from custom.
